# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-16 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_auto_20190611_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceselector',
            name='type',
            field=models.CharField(choices=[(b'str', b'Text'), (b'int', b'Integer'), (b'bool', b'Boolean'), (b'date', b'Date'), (b'list', b'List')], default=b'str', max_length=4),
        ),
    ]
